services:
  hackathon-api:
    build:
      context: ./src/Hackathon.Api
      dockerfile: Dockerfile
    container_name: hackathon-api
    ports:
      - "5043:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Supabase__Url=${SUPABASE_URL}
      - Supabase__ServiceRoleKey=${SUPABASE_SERVICE_ROLE_KEY}
      - Supabase__AnonKey=${SUPABASE_ANON_KEY}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - hackathon-network

  hackathon-frontend:
    build:
      context: ./src/HackathonUI/hackathon_flutter
      dockerfile: Dockerfile
    container_name: hackathon-frontend
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - hackathon-network
    depends_on:
      - hackathon-api

networks:
  hackathon-network:
    driver: bridge
